---
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    workingDir: /home/jenkins
    image: jenkins/inbound-agent:latest
  - name: docker
    workingDir: /home/jenkins
    image: docker:dind
    securityContext:
      privileged: true
  restartPolicy: Never