apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-deployment
  labels:
    app: robopd2-api
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: robopd2-api
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: robopd2-api
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: {{ include "chart.fullname" . }}-secret
        image: {{ .Values.deployment.robopd2Api.image.repository }}:{{ .Values.deployment.robopd2Api.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.deployment.robopd2Api.imagePullPolicy }}
        name: robopd2-api
        ports:
        - containerPort: 8000
          name: robopd2-api
        resources: {{- toYaml .Values.deployment.robopd2Api.resources | nindent 10 }}