apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ include "chart.fullname" . }}-ingress'
  labels: {{- include "chart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: www.robopd2.com
    http:
      paths:
      - path: /api(/|$)(.*)
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-service'
            port:
              number: 8000
        pathType: Prefix
  - host: robopd2.com
    http:
      paths:
      - path: /api(/|$)(.*)
        backend:
          service:
            name: '{{ include "chart.fullname" . }}-service'
            port:
              number: 8000
        pathType: Prefix
  tls:
  - hosts:
    - robopd2.com
    - www.robopd2.com
    secretName: robopd2-com-tls
