apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service
  labels:
    app: robopd2-api
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: robopd2-api
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service-nodeport
  labels:
    app: robopd2-api
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: robopd2-api
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30888
